services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: UserServiceDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 UserService.wsgi:application"
    volumes:
      - .:/app                    # Mount app code
      - ~/.aws:/root/.aws          # Mount AWS credentials
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:1234@db/UserServiceDB
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
